version: '3'

services:
  db:
    restart: always
    image: percona/percona-server:8.0.26-17
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - siberian-bridge

  php:
    restart: always
    image: siberian:php-fpm.7.3
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../siberian:/var/www/html
      - ./php/docker.conf:/etc/php/7.3/fpm/pool.d/
      - ./php/php.ini:/etc/php/7.3/fpm/php.ini
    ports:
      - "${SOCKETIO_RANGE}:${SOCKETIO_RANGE}"
    links:
      - db
    networks:
      - siberian-bridge

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ../siberian:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../siberian/var/apps/certificates/xtraball.com:/etc/nginx/ssl-certificates
    links:
      - php
    networks:
      - siberian-bridge

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=toor
    networks:
      - siberian-bridge

networks:
  siberian-bridge:
    driver: bridge